### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by RReverser** [Frommi/miniz_oxide#42]
`miniz_oxide` deep in dependency tree makes my project uncompilable on WASM with stable Rust.

I wanted to make a PR, but noticed that it's actually already fixed on master >2 months ago, but wasn't released to crates.io.

Can you please publish a new release?

**Comment by Frommi** [comment]
Hi!
Are you sure that `miniz_oxide` 0.2.0 is used and is not sufficiently new? Do you need last two commits? I won't have the ability to publish for the next ~2-3 days.

**Comment by iceiix** [comment]
Looking forward to this new release as well, but @RReverser note you don't have to use nightly as a workaround, adding this to your Cargo.toml works on stable:

```toml
[patch.crates-io]
miniz_oxide_c_api = { git = "https://github.com/Frommi/miniz_oxide", branch = "master" }
```
